// Shared icon registry for property features/amenities/services.
// The AI assigns each feature one of these KEYS at save time (stored on the
// property); the public page resolves the key → a lucide icon. A keyword
// fallback covers anything the AI didn't map, so a sensible icon always shows.
import {
  Wifi, Car, Waves, Coffee, UtensilsCrossed, Dumbbell, Sparkles, Wind, Flame,
  Tv, Mountain, Trees, ShieldCheck, Plane, PawPrint, Laptop, ConciergeBell,
  Bath, BedDouble, Sun, Snowflake, Droplet, Key, Calendar, Users, Music,
  Camera, Wine, Cigarette, Baby, Accessibility, ParkingCircle, Sailboat,
  Bike, Tent, Soup, GlassWater, Heart, CheckCircle2,
  // Expanded set
  WashingMachine, Refrigerator, Microwave, Utensils, Beer, Martini, CupSoda,
  ShowerHead, Zap, BatteryCharging, Lightbulb, Plug, Fan, Thermometer, Leaf,
  Sprout, Flower2, Sunrise, Sunset, Fish, Anchor, Ship, Map, Compass, Footprints,
  Luggage, Briefcase, Printer, Phone, Bell, Dog, Cat, Building2, Hotel, Bus,
  TrainFront, MountainSnow, Stethoscope, BookOpen, Library, Gamepad2, Dices,
  ShoppingBag, Store, Banknote, CreditCard, Globe, Languages, Clock, Shirt,
  Umbrella, Wheat, Telescope, Gift, Lock, Cctv, TreePalm, TreePine, Salad,
  Croissant, Cake, Headphones, Droplets,
  type LucideIcon,
} from "lucide-react"

// The canonical icon set. AI must return one of these keys.
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  // Connectivity & work
  wifi: Wifi,
  work: Laptop,
  business: Briefcase,
  printer: Printer,
  phone: Phone,
  language: Languages,

  // Parking & transport
  parking: ParkingCircle,
  car: Car,
  airport: Plane,
  transfer: Plane,
  bus: Bus,
  train: TrainFront,
  bike: Bike,
  boat: Sailboat,
  ship: Ship,
  anchor: Anchor,

  // Food & drink
  coffee: Coffee,
  dining: UtensilsCrossed,
  kitchen: Utensils,
  soup: Soup,
  salad: Salad,
  bakery: Croissant,
  cake: Cake,
  drinks: GlassWater,
  soda: CupSoda,
  wine: Wine,
  bar: Beer,
  cocktail: Martini,
  fridge: Refrigerator,
  microwave: Microwave,

  // Wellness & recreation
  gym: Dumbbell,
  spa: Sparkles,
  wellness: Heart,
  pool: Waves,
  medical: Stethoscope,
  games: Gamepad2,
  boardgames: Dices,
  music: Music,
  audio: Headphones,
  books: BookOpen,
  library: Library,
  camera: Camera,
  telescope: Telescope,

  // Climate & utilities
  ac: Wind,
  fan: Fan,
  cooling: Snowflake,
  heating: Flame,
  fireplace: Flame,
  temperature: Thermometer,
  power: Zap,
  charging: BatteryCharging,
  lighting: Lightbulb,
  outlet: Plug,
  water: Droplet,
  rain: Droplets,

  // Bath & room
  bath: Bath,
  shower: ShowerHead,
  bed: BedDouble,
  laundry: WashingMachine,
  clothing: Shirt,
  tv: Tv,

  // Outdoors & setting
  mountain: Mountain,
  snowmountain: MountainSnow,
  garden: Trees,
  nature: Leaf,
  plants: Sprout,
  flowers: Flower2,
  palm: TreePalm,
  pine: TreePine,
  farm: Wheat,
  beach: Umbrella,
  fishing: Fish,
  camp: Tent,
  trek: Footprints,
  compass: Compass,
  map: Map,
  sunrise: Sunrise,
  sunset: Sunset,
  sun: Sun,

  // Service, safety & misc
  concierge: ConciergeBell,
  reception: Bell,
  security: ShieldCheck,
  cctv: Cctv,
  lock: Lock,
  key: Key,
  pet: PawPrint,
  dog: Dog,
  cat: Cat,
  family: Baby,
  accessible: Accessibility,
  smoking: Cigarette,
  guests: Users,
  calendar: Calendar,
  clock: Clock,
  building: Building2,
  hotel: Hotel,
  shopping: ShoppingBag,
  store: Store,
  cash: Banknote,
  card: CreditCard,
  globe: Globe,
  luggage: Luggage,
  gift: Gift,
  check: CheckCircle2,
}

export const ICON_KEYS = Object.keys(ICON_REGISTRY)

// Keyword fallback when no AI key is stored. First match wins, so list the most
// specific patterns first. Kept generous so most free-text amenities resolve.
const FALLBACK: Array<[RegExp, string]> = [
  [/wi[- ]?fi|internet|broadband|connect|fibre|fiber/i, "wifi"],
  [/desk|workspace|work ?station|co[- ]?work|office|laptop|business cent/i, "work"],
  [/meeting|conference|boardroom/i, "business"],
  [/print|scan|copier/i, "printer"],
  [/phone|telephone|intercom|hotline/i, "phone"],
  [/multi[- ]?lingual|language|translat|english spoken/i, "language"],

  [/valet|garage/i, "parking"],
  [/free park|park|car ?port/i, "parking"],
  [/airport|air transport|flight|helicopter|heli/i, "airport"],
  [/transfer|shuttle|pick[- ]?up|drop[- ]?off|jeep|private car|chauffeur/i, "transfer"],
  [/\bbus\b|coach/i, "bus"],
  [/train|railway|metro/i, "train"],
  [/bicycle|bike|cycl|mountain bike/i, "bike"],
  [/raft|kayak|canoe|boating|boat ride/i, "boat"],
  [/sail|yacht|cruise/i, "boat"],

  [/breakfast|barista|espresso|cappucc|coffee|\btea\b|chai/i, "coffee"],
  [/restaurant|chef|fine din|à la carte|a la carte|full[- ]?board|half[- ]?board|meal plan|dinner|lunch|cuisine|menu/i, "dining"],
  [/kitchen|kitchenette|cook|stove|hob|cooktop|self[- ]?cater/i, "kitchen"],
  [/salad|vegetarian|vegan|organic|farm[- ]?to[- ]?table/i, "salad"],
  [/baker|pastr|croissant|bread/i, "bakery"],
  [/cake|dessert|sweets/i, "cake"],
  [/mini ?bar|fridge|refriger|cooler/i, "fridge"],
  [/microwave|oven/i, "microwave"],
  [/wine|cellar|vineyard|sommelier/i, "wine"],
  [/cocktail|mixolog/i, "cocktail"],
  [/\bbar\b|pub|lounge bar|beer|brew/i, "bar"],
  [/soft drink|soda|juice|refreshment/i, "soda"],
  [/welcome drink|beverage|drinks/i, "drinks"],

  [/gym|fitness|weights|workout/i, "gym"],
  [/yoga|meditat|pilates/i, "wellness"],
  [/spa|massage|sauna|steam|hammam|treatment/i, "spa"],
  [/wellness|holistic|ayurved|therap|rejuven|health/i, "wellness"],
  [/pool|swim|jacuzzi|hot ?tub|plunge/i, "pool"],
  [/clinic|doctor|medical|first ?aid|nurse|pharmac/i, "medical"],
  [/board ?game|chess|cards|ludo|carrom/i, "boardgames"],
  [/playstation|xbox|gaming|console|arcade|video game/i, "games"],
  [/library|reading|books?|magazine/i, "books"],
  [/music|speaker|sound system|live music|band/i, "audio"],
  [/photograph|camera|drone|gopro/i, "camera"],
  [/telescope|stargaz|astronom|night sky/i, "telescope"],

  [/air ?con|a\/c|aircon|climate control/i, "ac"],
  [/\bfan\b|ceiling fan/i, "fan"],
  [/cooling|chiller/i, "cooling"],
  [/fireplace|bonfire|campfire|wood stove|hearth/i, "fireplace"],
  [/heat|heater|warm|radiator|geyser|hot water/i, "heating"],
  [/thermostat|temperature/i, "temperature"],
  [/generator|backup power|inverter|\bups\b|power backup|electricity/i, "power"],
  [/\bev\b|electric vehicle|charging|charger/i, "charging"],
  [/light|lamp|reading light/i, "lighting"],
  [/socket|outlet|adapter|plug|universal/i, "outlet"],
  [/rain ?(water|shower)|monsoon/i, "rain"],

  [/bath|tub|ensuite|en[- ]?suite|toiletr|bathrobe|robe|amenity kit/i, "bath"],
  [/shower|rainfall shower|hot shower/i, "shower"],
  [/bed|linen|blanket|mattress|pillow|duvet|king|queen|twin|cot|crib/i, "bed"],
  [/laundry|washing machine|washer|dryer|launder/i, "laundry"],
  [/iron|clothes|wardrobe|closet|hanger/i, "clothing"],
  [/\btv\b|television|netflix|cinema|smart tv|cable|streaming|projector/i, "tv"],

  [/snow|himalay|peak|glacier/i, "snowmountain"],
  [/mountain|view|panoram|vista|scenic|balcon|terrace|rooftop/i, "mountain"],
  [/garden|lawn|orchard|courtyard|landscap/i, "garden"],
  [/forest|jungle|woods|nature|eco|green/i, "nature"],
  [/plant|greenery|botanic/i, "plants"],
  [/flower|bloom|floral/i, "flowers"],
  [/palm|tropical|coconut/i, "palm"],
  [/\bpine\b|conifer|alpine/i, "pine"],
  [/farm|agri|plantation|tea estate|tea garden|paddy/i, "farm"],
  [/beach|coast|seaside|sea ?view|lakeside|riverside|umbrella/i, "beach"],
  [/fish|angling/i, "fishing"],
  [/camp|tent|glamping|bonfire/i, "camp"],
  [/trek|hik|trail|walk|nature walk|expedition/i, "trek"],
  [/safari|wildlife|jungle drive|nature drive/i, "compass"],
  [/\bmap\b|guided|sightsee|excursion|day trip|tour/i, "map"],
  [/sunrise|dawn|early morning/i, "sunrise"],
  [/sunset|dusk|evening view/i, "sunset"],

  [/concierge|butler|host service|guest relations/i, "concierge"],
  [/reception|front desk|24[- ]?hour|24\/7|check[- ]?in/i, "reception"],
  [/housekeep|cleaning|daily clean|turndown|room service|service/i, "concierge"],
  [/security|safe|guard|gated|surveillance/i, "security"],
  [/cctv|camera surveillance|monitored/i, "cctv"],
  [/locker|safe(ty)? box|vault|lock/i, "lock"],
  [/keyless|smart lock|key card|access card|\bkey\b/i, "key"],
  [/pet[- ]?friendly|\bpets?\b/i, "pet"],
  [/\bdog\b|canine/i, "dog"],
  [/\bcat\b|feline/i, "cat"],
  [/child|kid|family[- ]?friendly|baby|infant|playground/i, "family"],
  [/wheelchair|accessib|disabled|step[- ]?free|barrier[- ]?free/i, "accessible"],
  [/non[- ]?smoking|smoking/i, "smoking"],
  [/group|guests|capacity|sleeps|occupanc/i, "guests"],
  [/event|wedding|celebration|function|banquet|calendar/i, "calendar"],
  [/clock|time|hours/i, "clock"],
  [/lodge|villa|cottage|bungalow|cabin|building|property|estate|mansion|heritage/i, "building"],
  [/hotel|resort|inn|guesthouse|homestay/i, "hotel"],
  [/shopping|boutique|souvenir|market/i, "shopping"],
  [/store|shop|provision|grocery/i, "store"],
  [/\bcash\b|atm|money exchange|forex|currency/i, "cash"],
  [/card|credit|payment|visa|mastercard/i, "card"],
  [/global|international|worldwide|globe/i, "globe"],
  [/luggage|baggage|porter|storage/i, "luggage"],
  [/gift|complimentary|welcome (kit|gift|hamper)|amenities kit/i, "gift"],
  [/water|drinking water|bottled|purif|filtered/i, "water"],
]

export function iconKeyForText(text: string): string {
  for (const [re, key] of FALLBACK) if (re.test(text)) return key
  return "check"
}

/** Resolve a feature to a lucide component, preferring the AI-assigned key. */
export function resolveFeatureIcon(text: string, iconMap?: Record<string, string> | null): LucideIcon {
  const aiKey = iconMap?.[text]
  if (aiKey && ICON_REGISTRY[aiKey]) return ICON_REGISTRY[aiKey]
  return ICON_REGISTRY[iconKeyForText(text)] ?? CheckCircle2
}
