"use client"

import { useState } from "react"
import { Sparkles, RefreshCw, TrendingUp, AlertTriangle, Minus } from "lucide-react"

type Insight = { title: string; detail: string; tone: "positive" | "warning" | "neutral" }

const TONE: Record<Insight["tone"], { icon: typeof TrendingUp; cls: string }> = {
  positive: { icon: TrendingUp, cls: "text-emerald-500" },
  warning: { icon: AlertTriangle, cls: "text-amber-500" },
  neutral: { icon: Minus, cls: "text-[#1B3A5C]/40" },
}

export function AiInsights() {
  const [insights, setInsights] = useState<Insight[] | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function run() {
    setLoading(true)
    setError(null)
    try {
      const res = await fetch("/api/admin/ai/insights")
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || "Failed")
      setInsights(data.insights as Insight[])
    } catch (e) {
      setError(e instanceof Error ? e.message : "Could not generate insights.")
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="bg-[#1B3A5C] rounded-2xl p-5 text-white">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-[#C9A96E]" />
          <h2 className="text-[15px] font-semibold">AI Insights</h2>
        </div>
        <button
          onClick={run}
          disabled={loading}
          className="flex items-center gap-1.5 text-[11px] font-medium text-white/70 hover:text-white transition-colors disabled:opacity-50"
        >
          <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} />
          {insights ? "Refresh" : "Generate"}
        </button>
      </div>

      {!insights && !loading && !error && (
        <p className="text-[12px] text-white/55 leading-relaxed">
          Generate live, AI-written analysis of this month&apos;s revenue, bookings, occupancy and risks — straight from your real data.
        </p>
      )}
      {loading && <p className="text-[12px] text-white/55">Analysing your latest data…</p>}
      {error && <p className="text-[12px] text-rose-300">{error}</p>}

      {insights && (
        <div className="space-y-3">
          {insights.map((ins, i) => {
            const t = TONE[ins.tone] ?? TONE.neutral
            const Icon = t.icon
            return (
              <div key={i} className="flex items-start gap-3">
                <Icon className={`h-4 w-4 mt-0.5 shrink-0 ${t.cls}`} />
                <div>
                  <p className="text-[13px] font-semibold leading-tight">{ins.title}</p>
                  <p className="text-[11px] text-white/60 leading-relaxed mt-0.5">{ins.detail}</p>
                </div>
              </div>
            )
          })}
          <p className="text-[9px] text-white/30 pt-1">Generated by AI from live data · verify before acting</p>
        </div>
      )}
    </div>
  )
}
